### ISSUE TITLE
Skip importing NO2 depositions

### ISSUE THREAD

**Issue by raymondnijssen** [opengeogroep/AERIUS-QGIS-plugins#15]
Calculator output GML seem to never contain NO2 depositions (anymore). Should they be removed from importing?

**Comment by Hilbrand** [comment]
NO2 depositions were never available, only NO2 concentrations. It depends on what one is looking at if it's relevant. For Wet Natuurbescherming (wnb) only deposition is relevant, so if one is looking for wnb only deposition is relevant to import.
