### ISSUE TITLE
Convert point layer to receptor points

### ISSUE THREAD

**Issue by raymondnijssen** [opengeogroep/AERIUS-QGIS-plugins#23]
The plugin allows uploading a custom receptor set as GML or RCP file. But it's currently hard for GIS users to convert their data into these formats. A simple save as receptor points processing algorithm would be very handy

**Comment by nicola-masey** [comment]
New branch ReceptorGML includes this functionality. The button for this in QGIS is simple text at the moment and should be designed before merging this into the main branch, along with providing documentation

**Comment by raymondnijssen** [comment]
https://github.com/opengeogroep/AERIUS-QGIS-plugins/commit/fd6d1bdf49b2144f8b00fec1d4e8b4a7a6f222e8
