### ISSUE TITLE
Unable to add roadType

### ISSUE THREAD

**Issue by CoenSPR** [opengeogroep/AERIUS-QGIS-plugins#33]
Currently the plugin lacks the ability to add a roadType to the GML when "generating calculator Input"

This results in errors when the GML is loaded into the AERIUS calculator on the website

**Comment by raymondnijssen** [comment]
Can you provide a generated gml file with such an error please?

**Comment by raymondnijssen** [comment]
Fixed: https://github.com/opengeogroep/AERIUS-QGIS-plugins/commit/fdcaa7f85e9bc326cb2a3191215e0331fb28275e
